require('dotenv').config();
const Datastore = require('@seald-io/nedb');
const db = new Datastore({ filename: './data/questions.db', autoload: true });

const QUESTIONS = [
  // Stage 1: O Cânon da Bíblia e a Inspiração
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'Quantos livros compõem a Bíblia Católica?',
    options:['66 livros (39 AT + 27 NT)','72 livros (45 AT + 27 NT)','73 livros (46 AT + 27 NT)','80 livros (53 AT + 27 NT)'],
    answer:2,
    explanation:'A Bíblia Católica tem 73 livros: 46 no Antigo Testamento (incluindo 7 deuterocanônicos) e 27 no Novo Testamento. As Bíblias protestantes têm 66, pois excluem os deuterocanônicos (CIC 120).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'Quais são os sete livros deuterocanônicos do Antigo Testamento aceitos pela Igreja Católica?',
    options:['Gênesis, Êxodo, Levítico, Números, Deuteronômio, Josué e Juízes','Tobias, Judite, 1-2 Macabeus, Sabedoria, Eclesiástico (Sirácida) e Baruc','Ester, Rute, Jó, Salmos, Provérbios, Eclesiastes e Cântico dos Cânticos','Daniel, Isaías, Jeremias, Ezequiel, Oseias, Amós e Miquéias'],
    answer:1,
    explanation:'Os 7 deuterocanônicos do AT são: Tobias, Judite, 1 Macabeus, 2 Macabeus, Sabedoria, Eclesiástico (Sirácida) e Baruc (com a Carta de Jeremias). São parte do cânon católico desde os primeiros séculos (CIC 120).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'O que significa dizer que a Bíblia é "Palavra de Deus"?',
    options:['Que Deus ditou palavra por palavra cada livro da Bíblia aos hagiógrafos','Que Deus, autor principal, se serviu dos hagiógrafos como autores reais, respeitando suas capacidades humanas, para transmitir o que queria','Que a Bíblia é apenas um livro humano inspirador sobre Deus','Que somente as palavras de Jesus nos Evangelhos são diretamente de Deus'],
    answer:1,
    explanation:'A inspiração bíblica não é ditado mecânico: Deus é o autor principal e os hagiógrafos são autores humanos verdadeiros, com estilo, cultura e limitações próprias; ambos os aspectos são reais (CIC 105-106).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'Qual é o princípio fundamental para a correta interpretação da Sagrada Escritura segundo o Catecismo?',
    options:['O intérprete individual tem autoridade suprema sobre o sentido do texto','A Escritura deve ser lida no mesmo Espírito em que foi escrita, levando em conta o contexto literário, a unidade da Escritura, a Tradição viva da Igreja e a analogia da fé','O sentido literal é o único válido; os sentidos alegórico e moral são irrelevantes','A Bíblia deve ser interpretada apenas à luz das ciências históricas modernas'],
    answer:1,
    explanation:'O Catecismo estabelece três critérios de interpretação: atenção ao conteúdo e unidade da Escritura, Tradição viva da Igreja, e analogia da fé — tudo lido no mesmo Espírito que a inspirou (CIC 111-114).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'O que é o "sentido literal" da Sagrada Escritura?',
    options:['O sentido que as palavras expressam em sua significação imediata e histórica, que é o fundamento dos demais sentidos','O sentido que proíbe qualquer interpretação simbólica ou alegórica','O sentido que só os teólogos doutores podem compreender','O sentido que contradiz a ciência moderna e deve ser reinterpretado'],
    answer:0,
    explanation:'O sentido literal é o que as palavras da Escritura significam diretamente, conforme as regras de interpretação normais; é a base sobre a qual se edificam os sentidos espirituais (alegórico, moral, anagógico) (CIC 116).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'O que é o "sentido alegórico" da Escritura?',
    options:['O sentido em que os textos do AT prefiguram e apontam para Cristo e a Igreja (tipologia bíblica)','O sentido em que cada palavra tem um significado secreto escondido','O sentido histórico das narrativas bíblicas','O sentido moral aplicado à vida cotidiana do cristão'],
    answer:0,
    explanation:'O sentido alegórico ou tipológico lê os fatos do AT como prefigurações de Cristo e da Nova Aliança: a travessia do Mar Vermelho prefigura o Batismo; o maná prefigura a Eucaristia (CIC 117).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'O que é a "Vulgata" e qual sua importância para a Igreja Latina?',
    options:['A primeira tradução da Bíblia para o grego, feita pelos 70 sábios em Alexandria','A tradução da Bíblia para o latim feita por São Jerônimo (séc. IV-V), que se tornou a versão oficial da Igreja Ocidental por mais de mil anos','A versão bíblica usada nas liturgias de língua portuguesa','A Bíblia original escrita em hebraico e aramaico'],
    answer:1,
    explanation:'A Vulgata (do latim vulgata editio = edição difundida) foi traduzida por São Jerônimo a pedido do Papa Dâmaso I (382-405) e se tornou a versão oficial da Igreja Latina, ratificada pelo Concílio de Trento (CIC 120).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'O que é a "Septuaginta" (LXX)?',
    options:['A tradução da Bíblia para o siríaco feita pelos primeiros cristãos','A tradução do AT do hebraico para o grego, feita por 70 (ou 72) sábios em Alexandria (séc. III-II a.C.), usada pelos autores do NT','A versão bíblica usada pelos Essênios no Mar Morto','O conjunto dos 70 discípulos de Jesus que escreveram os Evangelhos'],
    answer:1,
    explanation:'A Septuaginta (LXX) é a tradução do AT para o grego, feita em Alexandria entre os séculos III e I a.C.; foi a Bíblia dos primeiros cristãos e os autores do NT a citam com frequência (CIC 120).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'Qual é a grande divisão da Bíblia em duas partes e o que cada uma contém?',
    options:['Bíblia Hebraica (toda em hebraico) e Bíblia Grega (toda em grego)','Antigo Testamento (aliança de Deus com o povo de Israel antes de Cristo) e Novo Testamento (cumprimento em Cristo Jesus e a nova aliança)','Bíblia Pré-diluviana e Bíblia Pós-diluviana','Livros Canônicos (inspirados) e Livros Apócrifos (não inspirados)'],
    answer:1,
    explanation:'A Bíblia divide-se em Antigo Testamento (a aliança de Deus com Israel, prefiguração de Cristo) e Novo Testamento (o cumprimento em Jesus Cristo, a nova e eterna aliança) (CIC 121-123).' },
  { stage:1, theme:'O Cânon da Bíblia e a Inspiração',
    question:'O que o Catecismo afirma sobre a unidade entre Antigo e Novo Testamento?',
    options:['O AT foi superado e não tem mais valor para os cristãos','O NT está escondido no AT e o AT se torna claro no NT (Santo Agostinho): os dois formam uma única Revelação progressiva do mesmo Deus','O AT e o NT contradizem-se em muitos pontos','O AT pertence exclusivamente ao judaísmo e o NT ao cristianismo'],
    answer:1,
    explanation:'"O NT está escondido no AT, e o AT torna-se claro no NT" (Santo Agostinho): ambos os Testamentos formam uma única Revelação progressiva do mesmo Deus, culminando em Jesus Cristo (CIC 129).' },

  // Stage 2: O Pentateuco e os Livros Históricos
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O que é o "Pentateuco" e quais são seus cinco livros?',
    options:['Os cinco livros proféticos principais: Isaías, Jeremias, Ezequiel, Daniel e Amós','Os cinco primeiros livros da Bíblia: Gênesis, Êxodo, Levítico, Números e Deuteronômio, atribuídos à tradição mosaica','Os cinco livros sapienciais: Jó, Salmos, Provérbios, Eclesiastes e Cântico','Os cinco livros dos Macabeus sobre a revolta judaica'],
    answer:1,
    explanation:'O Pentateuco (do grego: cinco rolos) são os cinco primeiros livros da Bíblia: Gênesis, Êxodo, Levítico, Números e Deuteronômio — a Torah judaica, base da revelação do AT (CIC 702).' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O que narra o livro do Gênesis em seus dois primeiros capítulos?',
    options:['A história do povo de Israel desde Abraão até José no Egito','A criação do universo e do ser humano por Deus, a origem do mal pelo pecado original e as primeiras alianças divinas','A história de Adão e Eva como alegoria da evolução humana','As leis e os rituais do povo de Israel no deserto'],
    answer:1,
    explanation:'Gn 1-2 narra a criação por Deus em linguagem teológica (não científica): Deus cria tudo que existe por sua Palavra e o ser humano é criado à sua imagem; Gn 3 narra a queda e Gn 4-11 as consequências do pecado.' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'Qual é o evento central do livro do Êxodo?',
    options:['A construção do Templo de Salomão em Jerusalém','A libertação do povo de Israel da escravidão no Egito por Moisés e a aliança no Sinai','A conquista da Terra Prometida por Josué','A migração de Abraão da Mesopotâmia para Canaã'],
    answer:1,
    explanation:'O Êxodo narra a libertação de Israel do Egito por meio de Moisés (as pragas, a Páscoa, a travessia do Mar Vermelho) e a aliança no Sinai (os Dez Mandamentos) — fundamento de toda a fé de Israel (CIC 1334).' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O que são os "Dez Mandamentos" (Decálogo) e onde foram dados?',
    options:['As dez regras de convivência do povo de Israel no deserto','As leis dadas por Deus a Moisés no Monte Sinai, fundamento da ética judaica e cristã','As dez pragas enviadas sobre o Egito','As dez bênçãos pronunciadas por Moisés antes de morrer'],
    answer:1,
    explanation:'O Decálogo (Êx 20,1-17; Dt 5,6-21) são as dez palavras dadas por Deus a Moisés no Sinai; são o fundamento da lei moral natural e da ética judaico-cristã (CIC 2056-2063).' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O livro de Josué narra qual evento fundamental para a história de Israel?',
    options:['O reinado glorioso do Rei Salomão','A conquista e distribuição da Terra Prometida (Canaã) entre as doze tribos de Israel','A travessia do deserto por quarenta anos sob Moisés','O exílio do povo de Israel na Babilônia'],
    answer:1,
    explanation:'Josué narra a travessia do Jordão, a conquista de Canaã (especialmente Jericó) e a distribuição da Terra Prometida entre as doze tribos — cumprimento da promessa feita a Abraão.' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O que narra o livro dos Juízes?',
    options:['Os juízes civis que administravam a lei de Moisés no tribunal','O período entre a morte de Josué e o início da monarquia: ciclos de pecado, punição, clamor e salvação por meio de "juízes" levantados por Deus (Débora, Gedeão, Sansão etc.)','O processo judicial de Jesus diante de Pilatos','Os processos canônicos da Igreja primitiva'],
    answer:1,
    explanation:'Juízes descreve o período das tribos (séc. XII-XI a.C.) com o esquema recorrente: Israel peca → sofre opressão → clama a Deus → Deus levanta um juiz-libertador; inclui Débora, Gideão, Jefté e Sansão.' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'Quem foram os três grandes reis de Israel em sua época de ouro, segundo os livros de Samuel e Reis?',
    options:['Abraão, Isaac e Jacó','Saul, Davi e Salomão','Moisés, Josué e Samuel','Ezequias, Josias e Zorobabel'],
    answer:1,
    explanation:'Os três grandes reis da monarquia unida de Israel foram: Saul (1º rei), Davi (rei pastor e poeta) e Salomão (rei sábio que construiu o Templo). Após Salomão, o reino se dividiu em Israel e Judá.' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O que narra o livro de Rute e qual é sua importância teológica?',
    options:['A história da profetisa Rute que anunciou o Messias ao povo de Israel','A história da moabita Rute que, por amor e fidelidade a sua sogra Noemi, abraçou o povo e o Deus de Israel — tornando-se ancestral do Rei Davi e de Jesus','A história da conquista de Jericó por Rute, a espiã de Josué','A narrativa do casamento de Salomão com uma estrangeira'],
    answer:1,
    explanation:'Rute mostra que a fidelidade (hesed) ultrapassa fronteiras étnicas; a moabita Rute é bisavó de Davi (Rt 4,17) e aparece na genealogia de Jesus (Mt 1,5) — sinal de que a salvação é para todos os povos.' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'O que foram os "Macabeus" e o que os livros de 1-2 Macabeus narram?',
    options:['Os profetas que anunciaram o exílio da Babilônia','A família Macabeia (Hasmoneus) que liderou a revolta contra a helenização forçada por Antíoco IV Epifânio (séc. II a.C.) e reconquistou o Templo — comemorado na festa judaica de Hanuká','Os sacerdotes que reconstruíram o Templo após o exílio babilônico','Os escribas que fixaram o cânon da Bíblia hebraica em Jamnia'],
    answer:1,
    explanation:'Os livros dos Macabeus (deuterocanônicos) narram a revolta dos Macabeus (167-134 a.C.) contra Antíoco IV Epifânio, que profanou o Templo; 2Mc 12,46 fundamenta a doutrina do Purgatório e da oração pelos mortos.' },
  { stage:2, theme:'O Pentateuco e os Livros Históricos',
    question:'Qual é a importância teológica do livro de Tobias para a vida cristã?',
    options:['Fundamenta a doutrina do pecado original','Ensina sobre a providência de Deus na vida cotidiana, o valor do matrimônio, da oração e da esmola, e apresenta o arcanjo Rafael como mensageiro de Deus','Narra a criação do mundo de modo poético','Contém as profecias messias mais detalhadas do AT'],
    answer:1,
    explanation:'Tobias (deuterocanônico) é uma obra sapiencial sobre a providência divina, o poder da oração e da esmola, a fidelidade no matrimônio e o papel dos anjos; o arcanjo Rafael acompanha Tobias em sua jornada.' },

  // Stage 3: Os Livros Sapienciais e Salmos
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'Qual livro do AT é uma coleção de 150 poemas e orações que expressam toda a gama de emoções humanas diante de Deus?',
    options:['Provérbios','Eclesiastes','Salmos','Cântico dos Cânticos'],
    answer:2,
    explanation:'Os Salmos (Saltério) são 150 poemas litúrgicos atribuídos principalmente a Davi; cobrem louvor, súplica, lamentação, ação de graças e são o "coração orante" da Bíblia — usados na Liturgia das Horas (CIC 2585-2589).' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'Qual Salmo começa com as palavras que Jesus pronunciou na Cruz?',
    options:['Salmo 23 ("O Senhor é meu pastor")','Salmo 51 ("Misericórdia, ó Deus")','Salmo 22 ("Deus meu, Deus meu, por que me abandonaste?")','Salmo 130 ("Do fundo do abismo clamo a Vós")'],
    answer:2,
    explanation:'O Salmo 22 começa com "Deus meu, Deus meu, por que me abandonaste?" (Mt 27,46; Mc 15,34) — Jesus o pronunciou na Cruz; o salmo inteiro é uma profecia do sofrimento e glorificação do Messias (CIC 2605).' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'O livro de Jó trata de qual tema central?',
    options:['A origem do universo segundo a sabedoria hebraica','O sofrimento do justo: por que Deus permite que o inocente sofra? Jó mantém sua fé mesmo sem entender o mistério do sofrimento','O problema da morte e da ressurreição dos mortos','A recompensa dos bons e a punição dos maus ainda nesta vida'],
    answer:1,
    explanation:'Jó questiona o sofrimento do inocente e recusa as explicações simplistas dos amigos; Deus não explica o "por quê" do sofrimento, mas revela sua soberania e amor — Jó é um protótipo do Cristo sofredor (CIC 2315).' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'O que é o livro dos Provérbios?',
    options:['Uma coleção de profecia messiânica em forma poética','Uma coleção de máximas e ensinamentos práticos sobre a vida sábia e virtuosa, atribuídos principalmente à tradição salomônica','A narração poética da criação do mundo em seis dias','O livro das leis cerimoniais do Templo de Salomão'],
    answer:1,
    explanation:'Provérbios é uma antologia da sabedoria prática de Israel: máximas sobre trabalho, família, amizade, língua e temor do Senhor; "O temor do Senhor é o princípio da sabedoria" (Pr 9,10) é seu lema.' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'Qual livro do AT contém o famoso cântico "Vanidade das vaidades, tudo é vaidade"?',
    options:['Sabedoria','Provérbios','Sirácida (Eclesiástico)','Eclesiastes (Coélet)'],
    answer:3,
    explanation:'"Vanidade das vaidades, tudo é vaidade" (Ecl 1,2) é o tema central do Eclesiastes (Coélet): a busca de sentido nas riquezas, prazer e sabedoria mundanas acaba em vazio; somente Deus dá sentido à existência.' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'O Cântico dos Cânticos é um livro de poesia amorosa. Como a tradição judaica e cristã o interpreta?',
    options:['Apenas como poesia erótica sem valor religioso','Como a expressão do amor entre Deus e seu povo (Israel, no AT) e entre Cristo e a Igreja/alma humana (no NT) — o amor conjugal como imagem do amor divino','Como uma coleção de fórmulas mágicas do Oriente Médio','Como uma profecia sobre as tribulações do povo de Israel'],
    answer:1,
    explanation:'O Cântico dos Cânticos descreve o amor esponsal com beleza poética; a tradição o interpreta alegoricamente: o amor de Deus por Israel e de Cristo pela Igreja/alma — sendo a mais alta expressão mística da Bíblia (CIC 1611).' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'O livro da Sabedoria (deuterocanônico) foi escrito em qual língua e contém qual importante doutrina?',
    options:['Em hebraico, contendo a doutrina da criação do mundo em seis dias','Em grego, contendo ensinamentos sobre a imortalidade da alma, a providência divina e a personificação da Sabedoria como reflexo da glória de Deus','Em aramaico, contendo profecias sobre o exílio babilônico','Em latim, contendo as primeiras definições dogmáticas da Igreja'],
    answer:1,
    explanation:'O livro da Sabedoria foi escrito em grego em Alexandria (séc. I a.C.); contém a imortalidade da alma justa (Sb 3,1-9), a crítica à idolatria (Sb 13-14) e a Sabedoria como emanação da glória de Deus (Sb 7,25-26).' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'O Sirácida (Eclesiástico) é um livro deuterocanônico. Qual é sua peculiaridade entre os livros bíblicos?',
    options:['É o único livro bíblico escrito por uma mulher','É o único livro do AT cujo autor é conhecido pelo nome: Jesus Ben Sirá, escriba de Jerusalém (séc. II a.C.)','É o único livro profético do AT que menciona explicitamente o nome de Jesus','É o único livro bíblico que descreve a organização da Igreja cristã'],
    answer:1,
    explanation:'O Sirácida (Eclesiástico) foi escrito por Jesus, filho de Sirá (Sirácida), escriba de Jerusalém por volta de 180 a.C.; é o único livro do AT cujo autor identificamos pelo nome graças ao prólogo do seu neto.' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'Qual é o Salmo da misericórdia por excelência, atribuído a Davi após seu pecado com Betsabeia?',
    options:['Salmo 23','Salmo 91','Salmo 51 ("Miserere")','Salmo 119'],
    answer:2,
    explanation:'O Salmo 51 (Miserere: "Misericórdia, ó Deus, por tua bondade") é o grande salmo penitencial, atribuído a Davi após o pecado com Betsabeia e a morte de Urias. É rezado na Liturgia das Horas da Sexta-Feira.' },
  { stage:3, theme:'Os Livros Sapienciais e Salmos',
    question:'O que caracteriza a "Sabedoria" personificada no livro dos Provérbios (Pr 8) e da Sabedoria (Sb 7)?',
    options:['A Sabedoria é apresentada como um anjo criado antes do mundo','A Sabedoria é apresentada como presente com Deus desde antes da criação, participando de sua obra criadora — prefiguração do Logos (Verbo) divino encarnado em Cristo','A Sabedoria é uma deusa feminina assimilada da cultura egípcia','A Sabedoria é identificada com a lei mosaica exclusivamente'],
    answer:1,
    explanation:'A "Sabedoria" de Pr 8 e Sb 7 é personificada como companheira de Deus na criação; os Padres da Igreja viram nela a prefiguração do Logos (Jo 1,1) e uma preparação para a teologia trinitária (CIC 721).' },

  // Stage 4: Os Profetas Maiores
  { stage:4, theme:'Os Profetas Maiores',
    question:'O livro de Isaías contém a famosa profecia do "Servo Sofredor" em qual capítulo?',
    options:['Is 7,14','Is 40,3','Is 53','Is 60,1'],
    answer:2,
    explanation:'Isaías 53 descreve o "Servo Sofredor" que é ferido por nossos crimes, carrega nossas enfermidades e salva pela sua morte — cumprido em Jesus Cristo (At 8,32-35; CIC 601, 713).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'A profecia de Isaías 7,14 é fundamental para a fé cristã. O que ela anuncia?',
    options:['O retorno do povo do exílio babilônico para Jerusalém','Uma jovem/virgem conceberá e dará à luz um filho chamado Emanuel (Deus conosco) — interpretado pela Igreja como profecia do nascimento virginal de Jesus','A destruição de Assíria pelo exército de Davi','A construção do segundo Templo por Zorobabel'],
    answer:1,
    explanation:'"A virgem conceberá e dará à luz um filho e chamará seu nome Emanuel" (Is 7,14): Mateus (1,23) aplica diretamente esta profecia ao nascimento de Jesus de Maria Virgem (CIC 497).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'Qual profecia de Jeremias anunciou a Nova Aliança que seria cumprida em Cristo?',
    options:['Jr 1,5: "Antes de te formar no ventre materno, eu te conheci"','Jr 31,31-34: "Farei uma nova aliança... porei minha lei no íntimo deles, escreverei no seu coração"','Jr 29,11: "Sei os planos que tenho para vós, planos de prosperidade"','Jr 7,11: "Não fizestes desta casa uma caverna de ladrões?"'],
    answer:1,
    explanation:'Jr 31,31-34 anuncia a Nova Aliança: não gravada em pedra, mas no coração — cumprida em Cristo pela Eucaristia ("Este cálice é a nova aliança em meu sangue", Lc 22,20; CIC 762).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'O livro de Ezequiel contém a famosa visão do "vale dos ossos secos". O que essa visão simboliza?',
    options:['A ressurreição universal dos mortos no fim dos tempos','A restauração de Israel após o exílio babilônico, como ressurreição nacional; a tradição cristã também vê prefiguração da ressurreição dos mortos e da efusão do Espírito Santo (Ez 37)','A descida ao Sheol (mundo dos mortos) descrita alegoricamente','A punição dos pecadores pelo fogo do inferno'],
    answer:1,
    explanation:'A visão dos ossos secos (Ez 37,1-14) simboliza a restauração de Israel (morto no exílio) pela ação do Espírito de Deus; a tradição cristã vê prefiguração da ressurreição e do Pentecostes (CIC 715).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'O livro de Daniel contém famosas visões apocalípticas. Qual passagem é frequentemente citada no NT em relação a Cristo?',
    options:['Dn 3: Os três jovens na fornalha ardente','Dn 6: Daniel na cova dos leões','Dn 7,13-14: O "Filho do Homem" que recebe o domínio eterno — título messiânico favorito de Jesus','Dn 12,2: Os que dormem no pó da terra acordarão'],
    answer:2,
    explanation:'"Filho do Homem" (Dn 7,13-14) é a visão do ser celestial que recebe o domínio eterno de Deus; Jesus usa esse título para Si mesmo com frequência nos Evangelhos (Mc 14,62; CIC 664).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'O livro das Lamentações, atribuído a Jeremias, lamenta qual evento histórico?',
    options:['A morte do Rei Davi','A destruição de Jerusalém e do Templo pela Babilônia (586 a.C.) e o início do exílio','A conquista de Israel pela Assíria (722 a.C.)','A perseguição dos Macabeus por Antíoco IV (167 a.C.)'],
    answer:1,
    explanation:'As Lamentações são cinco poemas fúnebres sobre a destruição de Jerusalém por Nabucodonosor (586 a.C.) e o exílio babilônico; expressam o luto de Israel e a esperança na misericórdia de Deus (Lm 3,22-23).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'Qual profeta foi chamado pelo nome antes mesmo de nascer e viveu grande parte de seu ministério exilado na Babilônia?',
    options:['Isaías','Jeremias (Jr 1,5: "Antes de te formar no ventre, eu te conheci")','Ezequiel (que profetizou no exílio babilônico)','Baruc'],
    answer:1,
    explanation:'Jeremias foi chamado pelo nome antes do nascimento (Jr 1,5) e é o "profeta das lágrimas"; Ezequiel profetizou no exílio babilônico (593-571 a.C.). Ambos são Profetas Maiores.' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'O "Deutero-Isaías" (Is 40-55) começa com a famosa passagem: "Consolai, consolai meu povo". Qual é a visão central desses capítulos?',
    options:['A punição de Israel pelos pecados e o anúncio do exílio babilônico','O anúncio do retorno do exílio como novo Êxodo e a universalidade da salvação — "serás luz das nações" (Is 42,6; 49,6)','A reconstrução do Templo e das muralhas de Jerusalém','A chegada dos Reis Magos para adorar o Messias'],
    answer:1,
    explanation:'O Deutero-Isaías (Is 40-55) anuncia a libertação do exílio como novo Êxodo e apresenta o Servo Sofredor; o Israel restaurado será "luz das nações" — universalidade da salvação citada por Simeão (Lc 2,32; CIC 601, 713).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'O livro de Baruc (deuterocanônico) contém um célebre hino à Sabedoria. Qual é sua mensagem central?',
    options:['A Sabedoria habita nos filósofos gregos e deve ser buscada em Atenas','A verdadeira Sabedoria foi dada por Deus exclusivamente a Israel, identificada com o Livro dos mandamentos de Deus (a Torah) — "feliz somos nós, Israel" (Ba 4,4)','A Sabedoria é uma força cósmica impessoal que governa o universo','A Sabedoria estava oculta até a vinda do Messias'],
    answer:1,
    explanation:'Baruc identifica a Sabedoria com a Torah dada por Deus a Israel (Ba 3,9–4,4): "Este é o livro dos mandamentos de Deus... Felizes somos nós, Israel, que conhecemos o que agrada a Deus" (Ba 4,4).' },
  { stage:4, theme:'Os Profetas Maiores',
    question:'O que é a "vocação profética" segundo a Bíblia? O que distingue um profeta de um adivinho?',
    options:['O profeta prevê o futuro por técnicas de adivinhação; o adivinho apenas interpreta sonhos','O profeta é chamado por Deus para falar em seu nome (porta-voz de Deus), anunciando a vontade divina ao povo; não é primariamente um previsor do futuro, mas um intérprete da vontade de Deus no presente','O profeta é eleito pelo povo como seu representante diante de Deus','O profeta é um sacerdote que realizou milagres especialmente impressionantes'],
    answer:1,
    explanation:'O profeta bíblico (nabi: o que fala em nome de) é chamado por Deus para anunciar sua vontade; a profecia é primariamente proclamação (forth-telling), e secundariamente predição (fore-telling) (CIC 2115).' },

  // Stage 5: Os Profetas Menores e Livros Deuterocanônicos
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'Qual profeta menor anunciou: "Do teu seio, Belém Efrata... sairá o que há de dominar em Israel"?',
    options:['Amós','Oséias','Miquéias (Mq 5,1)','Zacarias'],
    answer:2,
    explanation:'Miquéias 5,1 profetiza que o Messias nascerá em Belém de Efrata — citado pelos sacerdotes a Herodes (Mt 2,6) quando os Magos perguntaram onde nasceria o Rei dos Judeus (CIC 522).' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O profeta Oséias usou sua própria vida (casamento com uma mulher infiel) para ilustrar qual mensagem?',
    options:['Que o divórcio é permitido em casos de adultério','O amor fiel (hesed) de Deus por Israel, mesmo quando Israel o trai como uma esposa infiel — Deus continua a amar e a buscar seu povo','A superioridade do celibato sobre o matrimônio','Que o pecado de Israel era punido com a pobreza'],
    answer:1,
    explanation:'Oséias viveu uma parábola profética: casou com Gômer, que o traiu, mas ele a retomou — imagem do amor fiel e misericordioso de Deus por Israel infiel; Oséias 11,1 ("Quando Israel era menino...") é citado em Mt 2,15.' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O profeta Amós é especialmente conhecido por sua mensagem sobre qual tema?',
    options:['A vinda do Espírito Santo sobre toda a humanidade','A justiça social: denúncia dos ricos que oprimem os pobres e do culto religioso vazio sem ética — "que flua o direito como água e a justiça como torrente caudalosa" (Am 5,24)','A chegada do Messias filho de Davi','A destruição do Templo de Salomão'],
    answer:1,
    explanation:'Amós (pastor de Tecoa, séc. VIII a.C.) é o profeta da justiça social: denuncia a opressão dos pobres pelos ricos e avisa que o culto a Deus é inútil sem a prática da justiça (Am 5,21-24).' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O livro de Jonas ensina principalmente qual mensagem teológica?',
    options:['Que os profetas devem fugir de suas missões para provar seu amor a Deus','A universalidade da misericórdia de Deus: Ele quer salvar todos os povos, incluindo os inimigos de Israel (Nínive)','Que o jejum de três dias é o principal ato de penitência','A importância da obediência imediata e sem questionamentos a Deus'],
    answer:1,
    explanation:'Jonas mostra que a misericórdia de Deus se estende além de Israel: Nínive, capital assíria (inimiga), se arrepende e é perdoada. Jesus cita Jonas como sinal da sua ressurreição (Mt 12,40; CIC 29).' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O profeta Zacarias contém profecias messiânicas. Qual é a famosa profecia cumprida na entrada de Jesus em Jerusalém?',
    options:['Zc 9,9: "Exulta muito, ó filha de Sião! Eis que vem teu Rei, justo e salvador, humilde, montado num jumento"','Zc 12,10: "Olharão para aquele que traspassaram"','Zc 14,4: "Seus pés estarão sobre o Monte das Oliveiras"','Zc 3,8: "Farei vir meu servo o Germe"'],
    answer:0,
    explanation:'Zc 9,9 é citado em Mt 21,5 e Jo 12,15 para descrever a entrada triunfal de Jesus em Jerusalém montado num jumentinho — o Messias que vem não como guerreiro, mas humilde e pacífico.' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O profeta Joel anuncia o "derramamento do Espírito sobre toda a carne" (Jl 3,1-5). Quando o NT diz que essa profecia se cumpriu?',
    options:['No Batismo de Jesus no Jordão','No Pentecostes (At 2,16-21): Pedro cita Joel para explicar o que aconteceu no derramamento do Espírito Santo sobre os discípulos','Na Transfiguração no Monte Tabor','Na Ressurreição de Jesus no domingo de Páscoa'],
    answer:1,
    explanation:'Joel 3,1-5 promete que Deus derramará seu Espírito sobre toda a carne; no Pentecostes, Pedro cita esse texto para explicar o fenômeno do dom de línguas sobre os discípulos (At 2,16-21).' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O profeta Malaquias anuncia o Precursor do Messias. Que texto específico é aplicado a João Batista?',
    options:['Ml 1,2: "Eu vos amei, diz o Senhor"','Ml 3,1: "Eis que envio meu mensageiro para preparar o caminho diante de mim" — o anjo/mensageiro identificado com João Batista','Ml 2,10: "Não temos todos o mesmo Pai?"','Ml 4,2: "Nascerá o sol de justiça"'],
    answer:1,
    explanation:'Malaquias 3,1 anuncia um mensageiro que preparará o caminho do Senhor; Jesus aplica este texto a João Batista (Mt 11,10; Mc 1,2), confirmando-o como o Elias prometido antes do Dia do Senhor.' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O livro de Judite (deuterocanônico) apresenta a heroína Judite como figura de qual realidade na tradição cristã?',
    options:['Da Igreja que vence os poderes do mal e de Maria que esmaga a cabeça da serpente (Gn 3,15)','Da fé individual que supera os obstáculos da vida cotidiana','Da vocação profética feminina nas comunidades de Israel','Da obediência cega às autoridades religiosas em tempo de perseguição'],
    answer:0,
    explanation:'Judite (que decapita Holofernes) é interpretada como figura de Maria que esmaga a cabeça da serpente (Gn 3,15) e da Igreja que vence os poderes do mal pela graça de Deus, não pela força humana.' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'2 Macabeus 12,39-46 é o principal texto bíblico usado pela Igreja para fundamentar qual doutrina?',
    options:['A doutrina da ressurreição corporal dos mortos','A doutrina do Purgatório e da oração pelos mortos: Judas Macabeu manda oferecer sacrifício pelos soldados mortos em pecado, porque "é uma santa e salutar ideia orar pelos mortos"','A doutrina da intercessão dos anjos pelos vivos','A doutrina da indulgência plenária concedida pelos papas'],
    answer:1,
    explanation:'2Mc 12,46: "É uma santa e salutar ideia orar pelos mortos para que sejam libertos dos seus pecados" — este texto fundamenta a doutrina católica do Purgatório e dos sufrágios pelos mortos (CIC 1032).' },
  { stage:5, theme:'Os Profetas Menores e Livros Deuterocanônicos',
    question:'O profeta Habacuc formulou uma pergunta que ressoa em toda a história da espiritualidade: qual?',
    options:['"Quando virá o Dia do Senhor para julgar os ímpios?"','"Por que me fazes ver a iniquidade? A violência está diante de mim... a lei perde o vigor e o direito nunca prevalece" — o clamor do justo que questiona a injustiça','Quando se abrirão as portas do céu para os justos perseguidos?','Por que o Senhor abandonou seu povo nas mãos dos inimigos?'],
    answer:1,
    explanation:'Habacuc questiona: por que Deus usa os babilônios (mais ímpios) para punir Israel? A resposta: "O justo viverá pela fé" (Hab 2,4) — citada por Paulo em Rm 1,17 e Gl 3,11, fundamento da justificação pela fé.' },

  // Stage 6: Os Evangelhos Sinóticos
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'Por que Mateus, Marcos e Lucas são chamados "Evangelhos Sinóticos"?',
    options:['Porque foram escritos simultaneamente por três autores trabalhando juntos','Porque "sinótico" significa "visão conjunta": esses três evangelhos podem ser lidos em paralelo (synopsis), pois compartilham material comum, ordem e perspectiva semelhantes','Porque foram os três primeiros Evangelhos a serem declarados canônicos pela Igreja','Porque os três evangelistas viveram na mesma cidade e compartilharam fontes idênticas'],
    answer:1,
    explanation:'"Sinótico" vem do grego syn-opsis (ver junto): Mt, Mc e Lc compartilham estrutura, episódios e fraseologia semelhantes — problema literário chamado "questão sinótica"; João tem perspectiva muito diferente.' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'O Evangelho de Marcos é considerado o mais antigo dos quatro Evangelhos. Qual característica literária o destaca?',
    options:['Sua extensão: é o mais longo dos quatro Evangelhos','Seu ritmo acelerado e imediato ("imediatamente" — euthys — aparece mais de 40 vezes), apresentando Jesus como o Filho de Deus em ação dinâmica','Sua estrutura em cinco discursos paralelos ao Pentateuco','Seu prólogo poético identificando Jesus com o Logos eterno'],
    answer:1,
    explanation:'Marcos é o mais curto e mais antigo (c.65-70 d.C.); destaca-se pelo estilo vivo e rápido ("imediatamente" repetido); sem narrativa da infância, começa diretamente com o Batismo e ministério público de Jesus.' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'O Evangelho de Mateus apresenta cinco grandes discursos de Jesus. Qual é o primeiro e mais famoso?',
    options:['O discurso missionário (Mt 10)','O Sermão da Montanha (Mt 5-7), que inclui as Bem-Aventuranças, o Pai-Nosso e o ensinamento sobre a lei nova','O discurso das parábolas (Mt 13)','O discurso escatológico (Mt 24-25)'],
    answer:1,
    explanation:'O Sermão da Montanha (Mt 5-7) é o primeiro e maior discurso de Jesus em Mateus; contém as oito Bem-Aventuranças (Mt 5,3-12), o Pai-Nosso (Mt 6,9-13) e o ensinamento sobre a lei nova (CIC 1716, 2763).' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'O Evangelho de Lucas é especialmente conhecido por apresentar qual aspecto da misericórdia de Jesus?',
    options:['O poder de Jesus sobre os demônios e a natureza','A misericórdia de Deus para com os pecadores, os pobres, as mulheres e os marginalizados; contém as parábolas da misericórdia: filho pródigo, ovelha perdida, dracma perdida','A identidade de Jesus como novo Moisés e cumprimento da Torah','O discipulado radical exigido por Jesus a todos os que o seguem'],
    answer:1,
    explanation:'Lucas destaca a misericórdia de Jesus: contém parábolas exclusivas (Filho Pródigo, Bom Samaritano), dá voz às mulheres e marginalizados, e apresenta Jesus como Salvador universal (Lc 2,14; CIC 2463).' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'O que são as "Bem-Aventuranças" (Mt 5,3-12; Lc 6,20-26)?',
    options:['Oito maldições contra os pecadores declaradas por Jesus no Sermão da Montanha','As oito proclamações de Jesus que revelam quem é verdadeiramente feliz no Reino de Deus — os pobres de espírito, os que choram, os mansos, os misericordiosos etc.','As oito condições para entrar no Templo de Jerusalém','Os oito mandamentos acrescentados por Jesus aos dez de Moisés'],
    answer:1,
    explanation:'As Bem-Aventuranças (beatitudes) descrevem o rosto do discípulo de Jesus e o caminho da verdadeira felicidade (blessedness): paradoxal em relação à sabedoria do mundo, revelam os valores do Reino (CIC 1716-1717).' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'A "Transfiguração" de Jesus (Mt 17,1-9; Mc 9,2-10; Lc 9,28-36) revelou o quê aos três apóstolos?',
    options:['A natureza humana de Jesus que estava sendo purificada pelo sofrimento','A glória divina de Jesus, sua conversa com Moisés e Elias sobre o Êxodo (morte) que realizaria em Jerusalém, e a voz do Pai confirmando-o como Filho amado','O plano de Jesus para a fundação da Igreja em Pedro','A ressurreição dos mortos que aconteceria após a morte de Jesus'],
    answer:1,
    explanation:'A Transfiguração antecipa a glória da Ressurreição: Jesus irradia luz divina, conversa com Moisés (a Lei) e Elias (os Profetas) sobre sua "partida" em Jerusalém, e o Pai proclama "Este é meu Filho amado" (CIC 554-556).' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'Qual é o "mandamento novo" dado por Jesus na Última Ceia segundo o Evangelho de João (Jo 13,34)?',
    options:['"Amarás o Senhor teu Deus com todo o teu coração, alma e mente"','"Amai-vos uns aos outros como eu vos amei" — o amor de Jesus pela humanidade torna-se o modelo e medida do amor entre os discípulos','Guardareis todos os mandamentos que eu vos dei desde o início da minha missão','Perdoai setenta vezes sete vezes a quem vos ofender'],
    answer:1,
    explanation:'"Amai-vos uns aos outros como eu vos amei" (Jo 13,34) é o mandamento novo: não apenas "ama ao próximo como a ti mesmo", mas com a medida do amor de Cristo que deu a vida (CIC 1823).' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'O que é a "Questão Sinótica" na crítica literária dos Evangelhos?',
    options:['A questão sobre se Jesus falou aramaico ou hebraico','O problema de explicar as semelhanças e diferenças entre os três Evangelhos Sinóticos: a teoria mais aceita é a prioridade de Marcos como fonte de Mateus e Lucas, mais a fonte "Q"','A questão sobre a autoria do quarto Evangelho','O debate sobre a historicidade dos milagres de Jesus nos Evangelhos'],
    answer:1,
    explanation:'A questão sinótica tenta explicar o material compartilhado e exclusivo de cada evangelho; a teoria das "duas fontes" (Marcos + Q) é a mais aceita academicamente, embora a Igreja não defina uma posição obrigatória.' },
  { stage:6, theme:'Os Evangelhos Sinóticos',
    question:'As "parábolas" de Jesus são um recurso literário especial. O que é uma parábola?',
    options:['Uma profecia direta sobre eventos futuros expressa em código','Uma comparação narrativa que usa a experiência humana cotidiana para revelar verdades sobre o Reino de Deus, exigindo do ouvinte uma decisão','Uma anedota humorística usada por Jesus para conquistar seus ouvintes','Um milagre narrado de modo alegórico para facilitar a compreensão'],
    answer:1,
    explanation:'A parábola (do grego parabolê) é uma comparação expandida: Jesus usa situações cotidianas (semeadura, pesca, banquete) para revelar os mistérios do Reino, chamando o ouvinte a uma decisão e conversão (CIC 546).' },

  // Stage 7: O Evangelho de João
  { stage:7, theme:'O Evangelho de João',
    question:'Com qual afirmação teológica começa o Evangelho de João, distinguindo-o dos Sinóticos?',
    options:['"No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus" (Jo 1,1)','A genealogia de Jesus desde Abraão até José','O anúncio do Batismo de Jesus no Jordão por João','A narrativa do nascimento de Jesus em Belém'],
    answer:0,
    explanation:'O Prólogo de João (Jo 1,1-18) identifica Jesus com o Logos (Verbo) eterno de Deus, preexistente à criação; "o Verbo se fez carne" (Jo 1,14) é o centro da teologia da Encarnação (CIC 456, 2787).' },
  { stage:7, theme:'O Evangelho de João',
    question:'O que são os "sete sinais" (milagres) no Evangelho de João?',
    options:['As sete parábolas do Reino narradas exclusivamente por João','Os sete milagres selecionados por João para revelar a glória de Jesus: água em vinho, cura do filho do oficial, paralítico, multiplicação dos pães, caminhada sobre as águas, cego de nascença e ressurreição de Lázaro','Os sete discursos de Jesus sobre o pão da vida','Os sete "eus sou" pronunciados por Jesus em João'],
    answer:1,
    explanation:'João seleciona 7 sinais (semeia) que revelam a glória de Cristo: Caná, cura à distância, paralítico de Betesda, multiplicação dos pães, caminhada sobre as águas, cego de nascença e ressurreição de Lázaro (Jo 2-11).' },
  { stage:7, theme:'O Evangelho de João',
    question:'O que é o "discurso do pão da vida" (Jo 6,22-71) e qual doutrina ele fundamenta?',
    options:['O ensinamento de Jesus sobre a oração e o jejum como pão espiritual','O longo discurso em que Jesus identifica a Si mesmo com o pão verdadeiro do céu e promete que quem comer sua carne e beber seu sangue terá a vida eterna — fundamento da Eucaristia','O discurso sobre a partilha dos bens materiais com os pobres como pão físico','A explicação da parábola da semente e do solo fértil como pão espiritual'],
    answer:1,
    explanation:'"Eu sou o pão da vida... quem comer minha carne e beber meu sangue tem a vida eterna" (Jo 6,48.54): João 6 é o grande discurso eucarístico, que a Igreja usa para fundamentar a presença real de Cristo na Eucaristia (CIC 1338).' },
  { stage:7, theme:'O Evangelho de João',
    question:'O que representa o "diálogo com Nicodemos" (Jo 3,1-21)?',
    options:['A conversa de Jesus com o sumo sacerdote antes de sua condenação','O encontro de Jesus com um fariseu instruído que vem de noite; Jesus anuncia o necessário nascimento de novo (água e Espírito) — fundamento teológico do Batismo, e Jo 3,16 ("Deus amou o mundo...")','O interrogatório de Jesus por Pilatos sobre sua identidade como rei','A cura do filho de Nicodemos pela fé de seu pai'],
    answer:1,
    explanation:'Nicodemos visita Jesus de noite (Jo 3): Jesus anuncia que "é preciso nascer de novo" pelo Batismo (água e Espírito); Jo 3,16 — "Deus amou o mundo de tal forma que entregou o seu Filho unigênito" — é o síntese do Evangelho (CIC 458, 1215).' },
  { stage:7, theme:'O Evangelho de João',
    question:'Quais são as sete afirmações "Eu Sou" (Ego Eimi) no Evangelho de João?',
    options:['Eu sou a Luz, o Caminho, a Verdade, a Vida, a Ressurreição, a Porta e o Pão','Eu sou o pão da vida; a luz do mundo; a porta das ovelhas; o bom pastor; a ressurreição e a vida; o caminho, a verdade e a vida; a videira verdadeira','Eu sou o Filho de Deus; o Rei dos Judeus; o Filho do Homem; o Messias; o Emanuel; o Senhor; o Salvador','Eu sou o Cordeiro de Deus; o Servo Sofredor; o Sacerdote eterno; o Profeta; o Rei; a Aliança; a Porta'],
    answer:1,
    explanation:'As sete afirmações "Eu Sou" de Jo: pão da vida (6,35); luz do mundo (8,12); porta das ovelhas (10,7); bom pastor (10,11); ressurreição e vida (11,25); caminho, verdade e vida (14,6); videira verdadeira (15,1). Cada uma revela um aspecto de Cristo (CIC 586).' },
  { stage:7, theme:'O Evangelho de João',
    question:'O que é o "Discurso de Adeus" de Jesus (Jo 13-17)?',
    options:['O discurso de Jesus no Templo, dias antes de sua morte, respondendo aos fariseus','Os longos ensinamentos de Jesus aos discípulos na Última Ceia: lavagem dos pés, novo mandamento do amor, promessa do Espírito Paráclito e a Oração Sacerdotal (Jo 17)','O sermão de Jesus na Sinagoga de Nazaré no início de seu ministério','O discurso de Jesus às multidões antes da multiplicação dos pães'],
    answer:1,
    explanation:'Os capítulos 13-17 de João são o "Discurso de Adeus" (ou "da Última Ceia"): lavagem dos pés (serviço), mandamento do amor, promessa do Paráclito (Espírito Santo) e a Oração Sacerdotal de Jesus ao Pai pelo seus discípulos (CIC 728, 2747).' },
  { stage:7, theme:'O Evangelho de João',
    question:'O que simboliza o episódio da "Samaritana" (Jo 4,1-42)?',
    options:['A condenação das mulheres que vivem em pecado','O encontro de Jesus com uma mulher de cinco maridos que revela: Jesus é a água viva que sacia toda sede espiritual; a salvação vai além de Israel; a adoração em espírito e verdade supera os templos','A primeira ordenação feminina na história do Evangelho','A purificação ritual da água segundo a lei mosaica'],
    answer:1,
    explanation:'A Samaritana (Jo 4): Jesus, ultrapassando barreiras étnicas e religiosas, revela a si mesmo como "água viva" que sacia toda sede; a adoração em espírito e verdade (Jo 4,23) não está presa a nenhum lugar sagrado (CIC 694, 728).' },
  { stage:7, theme:'O Evangelho de João',
    question:'O Evangelho de João termina com qual afirmação sobre seus propósitos?',
    options:['"Ide e fazei discípulos de todas as nações, batizando-os..."','Estes sinais foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais a vida em seu nome (Jo 20,31)','Eu, João, vi e ouvi estas coisas... a graça de Jesus seja convosco (Ap 22,8.21)','Tudo o que Jesus disse e fez está escrito neste livro para que sejais salvos (Jo 21,25)'],
    answer:1,
    explanation:'"Estes foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais a vida em seu nome" (Jo 20,31) — declaração explícita do propósito teológico do Evangelho de João.' },
  { stage:7, theme:'O Evangelho de João',
    question:'Qual episódio único no Evangelho de João demonstra simultaneamente a humanidade e a divindade de Jesus?',
    options:['A multiplicação dos pães e peixes','A ressurreição de Lázaro (Jo 11): Jesus chora diante do túmulo (humanidade) e em seguida ordena "Lázaro, vem para fora!" ressuscitando-o (divindade)','A cura do cego de nascença (Jo 9)','A caminhada de Jesus sobre as águas do mar de Tiberíades'],
    answer:1,
    explanation:'A ressurreição de Lázaro (Jo 11) é o 7º e maior sinal de João: Jesus chora com Maria e Marta (humanidade real), mas depois comanda a vida sobre a morte ("Lázaro, vem para fora!") — revelação plena de sua divindade (CIC 994).' },

  // Stage 8: Os Atos dos Apóstolos e as Cartas Paulinas
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'O livro dos Atos dos Apóstolos foi escrito por quem e qual é seu tema central?',
    options:['Por João Evangelista; narra as aparições de Jesus ressuscitado','Por Lucas, como segunda parte de sua obra; narra o nascimento e expansão da Igreja pelo poder do Espírito Santo, de Jerusalém até Roma','Por Paulo; narra suas três viagens missionárias','Por Pedro; narra a vida da comunidade primitiva de Jerusalém'],
    answer:1,
    explanation:'Atos, escrito por Lucas como continuação do terceiro Evangelho, narra a expansão da Igreja: de Jerusalém (Pentecostes), pela Judeia, Samaria (At 1,8), e até os confins da terra (Roma). O Espírito Santo é o verdadeiro protagonista.' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'O que narra Atos 2,1-13 e qual sua importância para a vida da Igreja?',
    options:['A eleição de Matias para substituir Judas Iscariotes','O Pentecostes: o Espírito Santo desce sobre os discípulos em forma de línguas de fogo; Pedro prega e três mil são batizados — "aniversário" da Igreja e cumprimento da promessa de Jesus','A conversão de Paulo no caminho de Damasco','O Concílio de Jerusalém sobre a circuncisão dos gentios'],
    answer:1,
    explanation:'Pentecostes (At 2): o Espírito Santo desce sobre os 120 discípulos; Pedro prega a ressurreição de Cristo; 3.000 são batizados. É o "nascimento público" da Igreja e o cumprimento da promessa do Paráclito (CIC 731-732).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'Qual é o tema central da Carta de Paulo aos Romanos?',
    options:['A organização litúrgica das comunidades cristãs','A justificação pela fé em Jesus Cristo: todos pecaram e precisam da graça de Deus; a salvação vem pela fé (Rm 3,21-26), não pelas obras da Lei','A ressurreição dos mortos e a volta de Cristo','O comportamento moral dos cristãos no casamento e na família'],
    answer:1,
    explanation:'Romanos é a grande exposição paulina da justificação pela fé: todos (judeus e gentios) estão sob o pecado (Rm 1-3); a justificação vem pela graça mediante a fé em Cristo (Rm 3,21-26); a vida nova no Espírito (Rm 8) (CIC 1994).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'O que Paulo ensina sobre o Corpo de Cristo em 1 Coríntios 12?',
    options:['Que a Igreja é um organismo perfeito que nunca erra','Que a Igreja é o Corpo de Cristo: muitos membros com diferentes carismas, mas um só Espírito e um só corpo — todos são necessários, nenhum é dispensável','Que somente os apóstolos formam o verdadeiro corpo de Cristo','Que o corpo físico de Jesus é o templo da Igreja'],
    answer:1,
    explanation:'1Cor 12: Paulo usa a metáfora do corpo para ensinar a unidade na diversidade da Igreja: o Espírito distribui dons diferentes a cada membro para o bem de todos; "o olho não pode dizer à mão: não preciso de ti" (1Cor 12,21) (CIC 791).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'O famoso "hino ao amor" de Paulo está em qual carta e capítulo?',
    options:['Rm 8','Ef 3','1Cor 13','Fl 2'],
    answer:2,
    explanation:'"Ainda que eu falasse as línguas dos homens e dos anjos... se não tiver amor (ágape), nada sou" (1Cor 13): o hino ao amor de 1Cor 13 é a definição paulina da caridade como virtude suprema (CIC 1826).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'O que Paulo ensina sobre a ressurreição em 1 Coríntios 15?',
    options:['Que apenas a alma ressuscita, não o corpo','Que a ressurreição de Cristo é o fundamento de toda a fé cristã: "se Cristo não ressuscitou, vã é a nossa fé"; a ressurreição dos mortos é certa como a de Cristo','Que a ressurreição acontece apenas espiritualmente no Batismo','Que somente os mártires ressuscitarão corporalmente'],
    answer:1,
    explanation:'"Se Cristo não ressuscitou, vã é a nossa fé" (1Cor 15,17): Paulo defende a ressurreição corporal dos mortos, fundada na ressurreição histórica e corporal de Cristo — centro e fundamento da fé cristã (CIC 638, 655).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'O que é o "hino cristológico" de Filipenses 2,5-11?',
    options:['O hino de louvor a Deus pai, criador do céu e da terra','O hino que descreve o rebaixamento (kenosis) de Cristo que, sendo Deus, assumiu a condição de servo e obedeceu até a morte na Cruz, sendo exaltado ao nome acima de todo nome','O cântico de louvor dos anjos no nascimento de Jesus','O hino ao amor esponsal entre Cristo e a Igreja descrito por Paulo'],
    answer:1,
    explanation:'"Tendo a condição divina... esvaziou-se a si mesmo... obedeceu até a morte... por isso Deus o exaltou" (Fl 2,6-9): este hino pré-paulino descreve a kenosis (esvaziamento) e a exaltação de Cristo (CIC 461, 2546).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'Qual carta de Paulo é considerada a "Magna Carta da liberdade cristã" e por quê?',
    options:['A Carta aos Romanos, pela doutrina da justificação','A Carta aos Gálatas: "Cristo nos libertou para a liberdade... não vos submetais de novo ao jugo da escravidão" (Gl 5,1) — Paulo defende que a salvação vem pela fé em Cristo, não pelas obras da Lei judaica','A Carta aos Efésios, pela doutrina da graça','A Carta aos Filipenses, pela alegria cristã em toda circunstância'],
    answer:1,
    explanation:'Gálatas é a carta mais combativa de Paulo: defende apaixonadamente a justificação pela fé (não pelas obras da Lei), a liberdade dos filhos de Deus e a universalidade da salvação: "não há mais judeu nem grego... todos são um em Cristo" (Gl 3,28) (CIC 1972).' },
  { stage:8, theme:'Os Atos dos Apóstolos e as Cartas Paulinas',
    question:'Qual texto paulino sobre o Matrimônio compara a union conjugal ao mistério de Cristo e a Igreja?',
    options:['1Cor 7, sobre o celibato e o casamento','Ef 5,25-32: "Maridos, amai vossas mulheres como Cristo amou a Igreja e se entregou por ela" — o amor conjugal como sacramento do amor de Cristo','Rm 7, sobre a luta entre a carne e o espírito','1Tm 3, sobre as qualidades do bispo casado'],
    answer:1,
    explanation:'Efésios 5,21-33 é o texto fundamental da teologia paulina do Matrimônio: o amor esponsal deve imitar o amor de Cristo pela Igreja (que deu a vida por ela); o matrimônio é "grande sacramento" (mysterion) (CIC 1616, 2365).' },

  // Stage 9: As Cartas Católicas e o Apocalipse
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'O que são as "Cartas Católicas" no Novo Testamento?',
    options:['Cartas escritas pelo papa para toda a Igreja','Sete cartas (Tiago, 1-2 Pedro, 1-2-3 João, Judas) chamadas "católicas" (universais) porque não são endereçadas a uma comunidade específica, mas à Igreja em geral','Cartas de Paulo para os gentios convertidos','As cartas enviadas por Maria aos apóstolos após a Ascensão'],
    answer:1,
    explanation:'As Cartas Católicas (universais) são: Tiago, 1 Pedro, 2 Pedro, 1 João, 2 João, 3 João e Judas — chamadas assim por não terem destinatário específico, mas serem dirigidas a toda a Igreja (CIC 120).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'A Carta de Tiago é famosa por defender qual princípio, aparentemente em tensão com Paulo?',
    options:['A necessidade do Batismo para a salvação dos gentios','Que a fé sem obras é morta (Tg 2,17): a fé autêntica necessariamente se manifesta em obras de amor — complemento da doutrina paulina da justificação pela fé','A primazia do papa sobre todos os cristãos','A ressurreição dos mortos como fundamento da esperança cristã'],
    answer:1,
    explanation:'"A fé sem obras é morta" (Tg 2,17): Tiago não contradiz Paulo, mas complementa — Paulo rejeita obras de lei para merecer a justificação; Tiago rejeita a fé meramente intelectual sem expressão em obras de amor (CIC 1815).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'A Primeira Carta de Pedro foi escrita para qual situação e contém qual ensinamento central?',
    options:['Para comunidades ricas que precisavam partilhar seus bens','Para cristãos em diáspora sofrendo perseguição: conforto na fé, chamada à santidade e à esperança na ressurreição — "sois povo conquistado, sacerdócio real, nação santa" (1Pd 2,9)','Para resolver disputas sobre o Batismo de adultos','Para corrigir erros sobre a ressurreição de Cristo na Grécia'],
    answer:1,
    explanation:'1 Pedro é escrita a cristãos em diáspora (perseguição) na Ásia Menor: incentiva a perseverança na fé, a santidade de vida e a esperança na salvação; "sois geração eleita, sacerdócio real" (1Pd 2,9) fundamenta o sacerdócio comum (CIC 1268).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'A Primeira Carta de João afirma qual verdade central sobre Deus?',
    options:['Que Deus é todo-poderoso e governa o universo com justiça absoluta','Que Deus é Amor (1Jo 4,8.16): "Quem não ama não conheceu a Deus, porque Deus é amor" — a definição mais profunda da natureza divina no NT','Que Deus é Luz e em Deus não há treva alguma','Que Deus é Espírito e os que o adoram devem adorá-lo em espírito e verdade'],
    answer:1,
    explanation:'"Deus é amor" (1Jo 4,8.16): esta afirmação de 1 João é a definição mais profunda de Deus no NT; o amor não é apenas um atributo divino, mas a essência de Deus — fundamento da vida trinitária e da moral cristã (CIC 221).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'O que é o livro do Apocalipse e a quem foi revelado?',
    options:['Um relato histórico da destruição de Jerusalém em 70 d.C., escrito por Lucas','Uma revelação (apokalypsis = desvelamento) dada a João em Patmos sobre os mistérios do combate entre o bem e o mal, o triunfo final de Cristo e a nova Jerusalém','Um livro de profecias políticas sobre os impérios mundiais','Uma coleção de visões dos mártires durante a perseguição de Nero'],
    answer:1,
    explanation:'O Apocalipse (Ap 1,1) é a revelação de Jesus Cristo a João em Patmos; usa linguagem simbólica (apocalíptica) para revelar o combate cósmico, o triunfo do Cordeiro imolado e a vitória final de Deus (CIC 2853).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'O que representa o "número da besta" (666) no Apocalipse?',
    options:['O número do anticristo que viverá no século XXI','Na linguagem apocalíptica, um número simbólico que representa a imperfeição (6 = humano sem Deus; 666 = a imperfeição triplicada), provavelmente referindo-se ao imperador romano Nero ou Domiciano','O número dos eleitos que serão salvos no fim dos tempos','A quantidade de anos que o anticristo governará a terra'],
    answer:1,
    explanation:'O 666 é número simbólico da "besta" (Ap 13,18); em gematria hebraica, "Nero César" soma 666; simboliza o poder imperial pagão que persegue a Igreja, não um personagem futuro específico (CIC 2853).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'O que é a "Nova Jerusalém" descrita nos capítulos finais do Apocalipse (Ap 21-22)?',
    options:['A reconstrução literal da cidade de Jerusalém no Oriente Médio','A visão escatológica do estado final de salvação: a habitação de Deus com os homens, onde "enxugará toda lágrima" e "não haverá mais morte, nem luto, nem choro, nem dor" (Ap 21,3-4)','O nome do novo estado de Israel fundado após o Holocausto','A Igreja militante na terra lutando contra os poderes do mal'],
    answer:1,
    explanation:'A Nova Jerusalém (Ap 21-22) é a visão do estado escatológico final: a plena comunhão de Deus com a humanidade redimida, sem morte, dor ou pecado — cumprimento de toda a criação e da história da salvação (CIC 1044, 1186).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'O "Cordeiro imolado" é a imagem central do Apocalipse. A quem ela se refere e o que significa?',
    options:['Ao povo de Israel martirizado ao longo da história','A Jesus Cristo: o "Cordeiro imolado desde a fundação do mundo" (Ap 13,8) que, pela sua morte e ressurreição, vence o mal, abre os selos da história e reina para sempre','A João Batista que foi degolado por Herodes','Ao cordeiro pascal da Páscoa judaica do Egito'],
    answer:1,
    explanation:'"O Cordeiro que foi imolado é digno de receber o poder, a riqueza, a sabedoria" (Ap 5,12): Cristo ressuscitado, que venceu pelo sacrifício da Cruz, é o centro da liturgia celeste e o Senhor da história (CIC 677, 2855).' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'Qual é o último versículo do Apocalipse e da Bíblia inteira?',
    options:['"Sede santos porque eu sou santo, diz o Senhor"','"A graça do Senhor Jesus seja com todos. Amém" (Ap 22,21)','Ide e pregai o Evangelho a toda criatura (Mc 16,15)','Eu sou o Alfa e o Ômega, o Primeiro e o Último (Ap 22,13)'],
    answer:1,
    explanation:'"A graça do Senhor Jesus seja com todos. Amém" (Ap 22,21) é o último versículo do Apocalipse e da Bíblia: a Escritura se encerra com uma bênção trinitária, como termina a liturgia — a Bíblia é um livro litúrgico.' },
  { stage:9, theme:'As Cartas Católicas e o Apocalipse',
    question:'A Carta aos Hebreus (de autoria incerta) apresenta Jesus principalmente como quê?',
    options:['O novo Moisés que dá uma lei mais perfeita','O Sumo Sacerdote eterno que, por seu próprio sangue, entrou de uma vez para sempre no Santuário celeste, oferecendo-Se como sacrifício perfeito e único (Hb 7-10)','O Filho de Davi que reina eternamente em Jerusalém','O profeta maior que todos os profetas do AT'],
    answer:1,
    explanation:'Hebreus apresenta Cristo como o Sumo Sacerdote eterno segundo a ordem de Melquisedec (Sl 110,4): sua auto-oferenda na Cruz é o único e perfeito sacrifício que cumpre e supera todos os sacrifícios do AT (CIC 1544).' },

  // Stage 10: A Leitura Bíblica na Vida da Igreja
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'O que é a "Lectio Divina" e quais são seus passos tradicionais?',
    options:['A leitura pública da Bíblia durante a Missa, presidida pelo diácono','Uma prática monástica de leitura orante da Escritura com quatro passos: Lectio (leitura), Meditatio (meditação), Oratio (oração) e Contemplatio (contemplação)','A leitura científica e histórico-crítica dos textos bíblicos','A tradução da Bíblia para novas línguas por especialistas'],
    answer:1,
    explanation:'A Lectio Divina é a leitura orante da Escritura: Lectio (ler o texto), Meditatio (ruminar a Palavra), Oratio (responder a Deus em oração), Contemplatio (repouso amoroso em Deus). O Papa Bento XVI a recomendou vivamente.' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'Qual é o nome do documento papal de Leão XIII (1893) que marcou o início do estudo moderno da Bíblia na Igreja?',
    options:['Divino Afflante Spiritu (Pio XII, 1943)','Providentissimus Deus (Leão XIII, 1893) — primeira encíclica moderna sobre a Sagrada Escritura, inaugurando o estudo científico católico da Bíblia','Dei Verbum (Vaticano II, 1965)','Verbum Domini (Bento XVI, 2010)'],
    answer:1,
    explanation:'"Providentissimus Deus" (1893) de Leão XIII inaugurou a renovação dos estudos bíblicos católicos; foi complementada por "Divino Afflante Spiritu" (1943) de Pio XII, que abriu as portas ao método histórico-crítico.' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'O que é a Constituição Dogmática "Dei Verbum" do Concílio Vaticano II?',
    options:['O documento sobre a liturgia que reformou a Missa','O documento sobre a Revelação divina: Escritura, Tradição e Magistério; afirma que a Bíblia deve ser a alma da teologia e que os fiéis devem ter acesso fácil à Palavra de Deus','O documento sobre a liberdade religiosa','O documento sobre as missões da Igreja no mundo moderno'],
    answer:1,
    explanation:'"Dei Verbum" (1965) é o documento do Vaticano II sobre a Revelação: declara a inseparabilidade de Escritura, Tradição e Magistério, afirma a inerrância nas matérias de salvação, e encoraja a leitura bíblica pelos fiéis (CIC 81, 107).' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'Como a Bíblia está presente na Liturgia da Missa?',
    options:['Apenas na homilia, quando o sacerdote cita versículos bíblicos','Em toda a Missa: nas antífonas, salmos, leituras (AT, Epístola, Evangelho), Credo, Oração dos Fiéis, Prefácio, Cânon Eucarístico e bênção final — a Missa é tecida de Escritura','Somente na Liturgia da Palavra (antes da consagração)','Apenas no Evangelho e na homilia'],
    answer:1,
    explanation:'A Liturgia é permeada de Escritura: da antífona de entrada ao canto de saída, tudo é Bíblia — Missa e Bíblia são inseparáveis. A Dei Verbum diz: "A Igreja alimenta-se da Escritura como do pão da vida" (DV 21; CIC 1100, 1154).' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'O que é o "Lecionário" usado na Missa?',
    options:['O livro de cantos e hinos usados durante a Missa','O livro litúrgico que contém as leituras bíblicas selecionadas para cada dia do ano litúrgico, organizadas em ciclos (A, B, C para domingos; I e II para dias de semana)','O livro das orações presidenciais do sacerdote na Missa','O catálogo de santos do calendário litúrgico anual'],
    answer:1,
    explanation:'O Lecionário (reformado após o Vaticano II) organiza as leituras em três ciclos dominicais (A: Mateus; B: Marcos; C: Lucas) e dois ciclos de dias úteis; em três anos, os fiéis ouvem a maior parte da Bíblia.' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'O que são os "Manuscritos do Mar Morto" (Qumran) e qual sua importância para a Bíblia?',
    options:['Textos pagãos que contradizem os Evangelhos, descobertos em 1947','Manuscritos hebraicos e aramaicos (sécs. III a.C.–I d.C.) descobertos em Qumran (1947), que incluem cópias de todos os livros do AT (exceto Ester) e confirmam a fidelidade de transmissão dos textos bíblicos','A versão original dos Evangelhos escrita em hebraico antes do grego','Cartas dos apóstolos não incluídas no cânon bíblico'],
    answer:1,
    explanation:'Os Manuscritos do Mar Morto (descobertos em 1947 em Qumran) incluem os documentos da comunidade essênia e cópias do AT mil anos mais antigas que os manuscritos até então conhecidos; confirmam a fidelidade de transmissão textual.' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'O que significa interpretar a Bíblia "segundo o sentido da Igreja" (sentire cum Ecclesia)?',
    options:['Aceitar apenas as interpretações dos papas medievais','Ler a Escritura na fé viva da Igreja: a interpretação não é individual e arbitrária, mas se realiza dentro da Tradição e sob a guia do Magistério, que é o intérprete autêntico','Rejeitar qualquer comentário bíblico de teólogos não ordenados','Limitar a leitura bíblica ao clero e aos religiosos'],
    answer:1,
    explanation:'"Sentire cum Ecclesia": a Escritura foi escrita dentro da comunidade de fé e deve ser lida nessa comunidade; o Magistério não está acima da Palavra de Deus, mas a serve como guardião e intérprete fiel (DV 10; CIC 119).' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'São Jerônimo disse: "A ignorância das Escrituras é a ignorância de Cristo." O que essa afirmação significa para a vida cristã?',
    options:['Os cristãos só podem conhecer a Cristo pelos sacramentos, não pela leitura bíblica','Que conhecer as Escrituras é encontrar o próprio Cristo que nelas fala; a leitura bíblica é encontro pessoal com a Pessoa de Jesus Cristo, não mero estudo literário','Que apenas os doutores em teologia podem conhecer a Cristo verdadeiramente','Que a ignorância bíblica condena automaticamente ao inferno'],
    answer:1,
    explanation:'"Ignoratio Scripturarum, ignoratio Christi est" (São Jerônimo): Cristo está presente na Escritura; ler a Bíblia é encontrá-Lo pessoalmente. O Papa Bento XVI cita esta frase no início de "Verbum Domini" (2010); CIC 133.' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'Qual é a estrutura do Evangelho de Lucas conhecida como "Magnificat" (Lc 1,46-55) e por quem é pronunciado?',
    options:['Uma profecia de Zacarias ao nascer João Batista','O cântico de louvor de Maria após a Anunciação e visita a Isabel: "Minha alma engrandece o Senhor..." — rezado na Liturgia das Horas das Vésperas de cada dia','A oração de Ana ao apresentar Samuel no Templo','O hino dos anjos no nascimento de Jesus em Belém'],
    answer:1,
    explanation:'O Magnificat (Lc 1,46-55) é o cântico de Maria, eco do cântico de Ana (1Sm 2): proclama a misericórdia de Deus que eleva os humildes e derruba os poderosos; é o hino das Vésperas da Liturgia das Horas (CIC 722, 2619).' },
  { stage:10, theme:'A Leitura Bíblica na Vida da Igreja',
    question:'O que é a "Bíblia de Jerusalém" e por que é especialmente usada no Brasil?',
    options:['Uma Bíblia ilustrada produzida em Jerusalém para turistas','Uma tradução crítica da Bíblia produzida pela Escola Bíblica de Jerusalém (dominicanos), com notas exegéticas extensas; no Brasil é uma das principais referências acadêmicas e pastorais, junto com a Bíblia da CNBB e a Edição Pastoral','A primeira Bíblia traduzida para o português pelo padre Antônio Vieira','A versão oficial da Bíblia aprovada somente para o uso litúrgico no Brasil'],
    answer:1,
    explanation:'A Bíblia de Jerusalém (École Biblique et Archéologique Française de Jérusalem) é uma tradução crítica das línguas originais com extensas notas; é referência acadêmica e pastoral, especialmente nas edições brasileiras da Paulus.' },
];

(async () => {
  const removed = await db.removeAsync({ trailId: 'trail_6' }, { multi: true });
  console.log(`Removidas ${removed} questões antigas de trail_6`);

  const now = Date.now();
  const docs = QUESTIONS.map(q => ({
    trailId: 'trail_6',
    level: 1,
    stage: q.stage,
    theme: q.theme,
    question: q.question,
    options: q.options,
    answer: q.answer,
    explanation: q.explanation,
    createdAt: now,
  }));

  let ok = 0;
  for (const doc of docs) {
    try { await db.insertAsync(doc); ok++; }
    catch (e) { console.error('Erro:', e.message); }
  }
  console.log(`Inseridas ${ok} questões`);

  await new Promise(res => db.compactDatafile(res));

  for (let s = 1; s <= 10; s++) {
    const count = (await db.findAsync({ trailId: 'trail_6', stage: s })).length;
    console.log(`Stage ${s}: ${count} questões ${count === 10 ? '✓' : '⚠ VERIFIQUE'}`);
  }
  const total = (await db.findAsync({ trailId: 'trail_6' })).length;
  console.log(`\nTotal trail_6: ${total} questões ${total === 100 ? '✓ PERFEITO' : '⚠ INCOMPLETO'}`);
  process.exit(0);
})();
